### ISSUE TITLE
USER RESEARCH TASK 

### ISSUE THREAD

**Issue by MercyTolu** [zuri-training/proj_fetch-metadata_team_81#11]

**Comment by jibobol** [comment]
It was fun working with my team mates as we conducted the research.

**Comment by babaj301** [comment]
The research process was really insightful. I enjoyed working with the research team

**Comment by oluwatosinmichael** [comment]
The process of research was interesting as i got to learn what metadata was about for the first time and it also exposed me to working in a team, which i really enjoyed.
