### ISSUE TITLE
STYLE GUIDES TASK

### ISSUE THREAD

**Issue by MercyTolu** [zuri-training/proj_fetch-metadata_team_81#12]
Color system  @jibobol 
Typography @jibobol 
Input fields @OnojaBlinks 
Buttons @Amazon100 
grid system @jibobol 
Iconography @Smiles0 
Alerts and notifications @Amazon100 
Typography @PreciousBello

**Comment by PreciousBello** [comment]
It was great working on the style guide used for the team's design. It was also a great opportunity to grow and learn more from team members that contributed.

**Comment by jibobol** [comment]
it was a pleasure to work hand-in-hand with other designers to come up with the style guide used in the design process.
