### ISSUE TITLE
LANDING PAGE

### ISSUE THREAD

**Issue by MercyTolu** [zuri-training/proj_fetch-metadata_team_81#13]
WEB VIEW
1. Wireframe
2. Lo-fi
3. Hi-fi

MOBILE VIEW
1.Hi-fi

**Comment by jibobol** [comment]
I started with a sketch before proceeding to the wireframe, low-fi then high-fi. I ran into some challenges such as going back to add or remove some elements which affected the spacing of the page making me edit the wireframe, low-fi and high-fi and the mobile version as well.
