### ISSUE TITLE
SIGN UP PAGE

### ISSUE THREAD

**Issue by MercyTolu** [zuri-training/proj_fetch-metadata_team_81#14]
Wireframe
Lo-fi
Hi-fi

with different states for the input fields and buttons

**Comment by Aladeboluwatife** [comment]
Designing the sign up page and the different states was quite enjoyable for me. Through the training I underwent with zuri and personal practices was what helped me. I was honestly able to do everything by the books and check for errors if there’s any. Once I started designing I hardly went on break at a point I was forced to eat. I really enjoyed the process and also how cooperative my team is. We were willingly to help one another at every step of the way.
