### ISSUE TITLE
DASHBOARD HI-FI

### ISSUE THREAD

**Issue by MercyTolu** [zuri-training/proj_fetch-metadata_team_81#16]
Mobile view and web view

1. Default screen
2. Uploaded screen
3. Analyzing screen
4. Analyzed screen
5. Files screen
6. Activity screen
7. Help and support screen
8. Settings screen

**Comment by jibobol** [comment]
I came up with a sketch that fits my team's desired product i.e the pages an authorized user will have access to before designing the High-fi and mobile version. Pretty fun to do as I collected ideas from my team mates and adjusted some elements to fit perfectly with our desired goal .
