### ISSUE TITLE
DASHBOARD WIREFRAME & LO-FI (WEBSITE)

### ISSUE THREAD

**Issue by MercyTolu** [zuri-training/proj_fetch-metadata_team_81#17]
WEB VIEW

1. Default screen
2. Uploaded screen
3. Analyzing screen
4. Analyzed screen 
5. Files screen
6. Activity screen
7. Help and support screen
8. Settings screen
9. 404 error screen

**Comment by oluwatosinmichael** [comment]
In the process of creating the wireframe and lowfi on the figma board which the team had already deliberated on before hand, i learnt a lot and i also enjoyed working with my teammates.

**Comment by oluwatosinmichael** [comment]
In the process of creating the wireframe and lowfi on the figma board which the team had already deliberated on before hand, i learnt a lot and i also enjoyed working with my teammates.
